### ISSUE TITLE
Support for FontAwesome Pro icons

### ISSUE THREAD

**Issue by jceb** [x64Bits/solid-icons#1]
Thank you for the icons wrapper. How would I go about integrating it with fontawesome pro icons?

**Comment by x64Bits** [comment]
Hi @jceb thanks to you for using it, it doesn't sound bad but I have not used Font Awesome Pro before, I don't know how viable its integration is, if it has the same structure as its free pair it is possible.

**Comment by jceb** [comment]
I just stumbled upon this issue with a potential solution that could also work for solid-icons: https://github.com/antfu/unplugin-icons/issues/12

**Comment by x64Bits** [comment]
Hello @jceb, I am sorry I did not answer you before, I thought a lot about how to add this functionality to the library but it seems to me that it is out of reach for what is necessary so far, which is to use all the icons available so far in the lib, I will be working that those of Ionicons are completely corrected and if it is possible to add more packages.

I find that unplugin-icons works very well for the need you mention.
