### ISSUE TITLE
Impossible to make stroke width smaller

### ISSUE THREAD

**Issue by teenjuna** [x64Bits/solid-icons#12]
Hi! I'm trying to use the heroicons pack, but I'm unable to make the stroke-width of the icon smaller (both with style attribute and with tailwind class). Making it bigger is no problem.

**Comment by x64Bits** [comment]
Hi @teenjuna, thanks for reporting this, i'll see what happens

**Comment by teenjuna** [comment]
Hey @x64Bits, was you able to find anything or you hand't have a change yet?

**Comment by x64Bits** [comment]
I have been trying and it is certainly possible to decrease the border in Heroicons but it would be necessary to replace the common SVG element that all the packages use, I would recommend going to CSS to solve this, also i'm open if something occurs to you.
