### ISSUE TITLE
The icon is a black square (bug?)

### ISSUE THREAD

**Issue by pheianox** [x64Bits/solid-icons#16]
![image](https://user-images.githubusercontent.com/77569421/198841838-76930853-cdeb-421a-9758-97ed508b14ee.png)

App.tsx
```tsx
import { Component } from "solid-js"
import * as TbIcon from 'solid-icons/tb'

export const App: Component = () => {
  return (
    <div>
      <TbIcon.TbRectangle size={50} />
    </div>
  )
}
```
tailwindcss config
```cjs
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,css,md,mdx,html,json,scss}",
  ],
  darkMode: "class",
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
};
```
dependencies
```json
"devDependencies": {
    "autoprefixer": "^10.4.13",
    "daisyui": "^2.36.1",
    "postcss": "^8.4.18",
    "tailwindcss": "^3.2.1",
    "typescript": "^4.8.2",
    "vite": "^3.0.9",
    "vite-plugin-solid": "^2.3.0"
  },
"dependencies": {
    "solid-icons": "^1.0.3",
    "solid-js": "^1.5.1"
  }
```
Stack: create-tw (SolidJS, Typescript, Daisyui)

**Comment by pheianox** [comment]
Live Example: https://stackblitz.com/edit/daisyui-solidjs-dwaur1?file=src/App.jsx

**Comment by pheianox** [comment]
Please help ASAP, maybe should reduce version to the stable one or what's the deal?

**Comment by pheianox** [comment]
Solved by reducing solidjs version from `1.5.1` back to `1.5.0`

**Comment by pheianox** [comment]
Possible bug. Works fine at solidjs v1.5.0

**Comment by x64Bits** [comment]
In the live example I couldn't reproduce the error with the versions you mentioned nor with the most recent ones of solid-js, you can check if updating `solid-icons` -> `1.0.4` helps to solve this? there were changes in `solid-js` recently and that changes broke the lib.

**Comment by pheianox** [comment]
Yes, everything works fine now

Thank you, man!
