### ISSUE TITLE
Color in class needs to be !important now.

### ISSUE THREAD

**Issue by pinko64** [x64Bits/solid-icons#19]
I used to be able to do this:
` <Available
          class={store?.me?.status === "available" && s({ color: col })}
          onClick={() => setMyStatus("available")}
        />
`

But now there is somewhy "currentcolor" set as color stylesheet... so i have to do:
` <Available
          class={store?.me?.status === "available" && s({ `${col} !important` })}
          onClick={() => setMyStatus("available")}
        />
`

So there was a breaking change in some patch a while ago. Why do i need to ovverride the color style now? º¿º¬

**Comment by x64Bits** [comment]
Sorry for the delay @pinko64, what you mention is correct, there was a change that affected when you declare the class in the icon, I will see if it does not conflict with the other use cases and I will try to send a new version, greetings.
