### ISSUE TITLE
icons are not supporting tailwind

### ISSUE THREAD

**Issue by DaliborTrampota** [x64Bits/solid-icons#23]
Hi, I want to change the icon color on hover but it does not work. I'm porting from react to solidjss and react icons support it.

this is how its setup
<PencilIcon size={24} className='w-5 h-5 !hover:text-green'/>

how can I change the color on hover?

**Comment by x64Bits** [comment]
Certainly there was a problem for the css selectors to affect the colors and you had to use `color` directly, this is possibly corrected in 1.0.5, regards.

**Comment by x64Bits** [comment]
I have confirmed, from version 1.0.5 the problem to set colors with tailwind has been fixed.
