### ISSUE TITLE
Unable to change color of IoTodayOutline icon

### ISSUE THREAD

**Issue by siduck** [x64Bits/solid-icons#3]
I tried changing its color to white but it just stays black 

<IoTodayOutline size={24} color="#ffffff"/>

![image](https://user-images.githubusercontent.com/59060246/163496094-8aafb539-d509-4d9f-9f4c-b121145e5776.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/163794051-a717fbad-6244-4e3d-a136-6daf6e593f36.png)

@x64Bits any idea?

**Comment by x64Bits** [comment]
Hi @siduck i'm already looking at a solution for this, i need to review.

**Comment by siduck** [comment]
Related issues : 

https://github.com/ionic-team/ionicons/issues/784
https://stackoverflow.com/questions/60906416/cant-change-the-stroke-color-of-ionicon-5-outline-set

**Comment by x64Bits** [comment]
I have already found what the problem is my first iteration this week i managed to solve the specific problem that we have with the calendar icon all the icons of ionic icons 5 with forms based on Lines, but there are icons that continue to present problems i plan to solve it to send everything ready this coming week.

**Comment by x64Bits** [comment]
Hi @siduck, sorry for not following up on this issue correctly, I published changes in the latest version that partially solve many of the icons involved, almost all of them from Ionicons, I'm not entirely convinced of the results, I'll try another iteration to improve that specific set, why I think you are the only one with these problems.

**Comment by siduck** [comment]
@x64Bits it works now, thanks a lot!

![image](https://user-images.githubusercontent.com/59060246/168782220-fc2f439b-dc81-4325-94a9-eba9521525dc.png)
