### ISSUE TITLE
Update HeroIcons

### ISSUE THREAD

**Issue by awhitford** [x64Bits/solid-icons#34]
The documentation says that the HeroIcons version is 1.0.3, but 2.0.17 is out:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/123887/236796522-d7209627-35a0-4a5a-a4b1-a773664cb832.png">
_Can this package be updated?_

**Comment by x64Bits** [comment]
Already done on 1.0.6, thanks for notice 👍  https://github.com/x64Bits/solid-icons/pull/36
