### ISSUE TITLE
Module parse failed: Unexpected token in v 1.0.6 (in <= 1.0.5 not reproduced)

### ISSUE THREAD

**Issue by Hagriel** [x64Bits/solid-icons#37]
`ERROR in ./node_modules/solid-icons/ri/index.js 7496:27
Module parse failed: Unexpected token (7496:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       }, props)
|   }
>   export function RiHealth & MedicalBrainFill (props) {
|       return IconTemplate({
|         a: {"viewBox":"0 0 24 24"},
`

**Comment by x64Bits** [comment]
Thanks for notifying about this, I have already sent a new version (1.0.7) with this solved, PR related: https://github.com/x64Bits/solid-icons/pull/38.

This reminds me that I should write a test to run before publishing a new version checking that each icon works well.
