### ISSUE TITLE
Remix Icon's color gets broken since v1.0.5

### ISSUE THREAD

**Issue by lqmanh** [x64Bits/solid-icons#39]
In commit https://github.com/x64Bits/solid-icons/commit/1abc8e480f7c1c1c559ca569fc543beff83102ad, the following change made Remix Icon's color broken:

```
-fill="currentColor"
+color={props.color || "currentColor"}
```

I'm not sure if this is the right place to fix it, or Remix Icon itself (https://github.com/Remix-Design/RemixIcon/issues/433), but could we re-add `fill` property as a workaround at least?

Thanks in advance.

**Comment by x64Bits** [comment]
Hi @lqmanh, thanks for notifying about it 🙌🏼, i just sent a new [version (1.0.8)](https://www.npmjs.com/package/solid-icons/v/1.0.8) that add the `fill="currentColor"` on the path only for remix icons set.

Here a codesandbox with the example: https://codesandbox.io/p/sandbox/silly-buck-sbc4fu

**Comment by lqmanh** [comment]
Working now, thanks a bunch ❤️
