### ISSUE TITLE
break apart by sources please

### ISSUE THREAD

**Issue by tomByrer** [x64Bits/solid-icons#4]
Seems like to get only 2 icons, I have to `npm i` all 14156 icons on my drive?  If true, maybe split each icon family as a separate package?
I'd rather save my bandwidth for cat videos ;)

**Comment by x64Bits** [comment]
Hi Tom, i am going to consider this very seriously, i also suffer downloading heavy size libraries and it seems fair to me, i just need to check how much i have to change to publish separate packages but it seems quite logical, i have seen that many libraries are doing it.

**Comment by tomByrer** [comment]
Thanks for your consideration!

TBH, for the project I looked at this for, I just [copy/pasted the raw SVG](https://github.com/tanvesh01/motion-signals/blob/main/examples/src/components/AnimatingCounter.jsx#L40).  An online icon searcher that had a way to simply copy the raw SVG could be another workaround.

**Comment by x64Bits** [comment]
I think we will postpone this because it represents additional work and I don't think we are a very big lib yet, what do you think?

**Comment by x64Bits** [comment]
I'm already adding the option on the website to copy the JSX component and the SVG, thanks for giving the idea, this week I sent this.

**Comment by x64Bits** [comment]
A new version of the website has already been launched where two buttons have been added to copy the icon in different formats, JSX and SVG.

**Comment by tomByrer** [comment]
Thanks for your hard work!  I like the JSX & SVG options also.
