### ISSUE TITLE
Doesn't work on Astro 2.6

### ISSUE THREAD

**Issue by suhaylmv** [x64Bits/solid-icons#41]
I moved my project to a newer version of Astro (2.6) and all the solid-icons (except the hamburger one which I used for the navbar) I've used appear in the DOM but are invisible. I didn't have this issue with the older version of Astro 2.3

**Comment by x64Bits** [comment]
Hi thanks for waiting, can you take a look at the `1.0.10` version? recently i sent a solution for that.

**Comment by suhaylmv** [comment]
Now it works good. Thank you for fixing this issue
