### ISSUE TITLE
class prop d

### ISSUE THREAD

**Issue by pinko64** [x64Bits/solid-icons#5]
Props  doesn't react to solidjs signals.

For example the next won't work:

`` <VscHome
          size={64}
          class={pathname() != "/home" ? cssIcon : cssIconSelected}
          onClick={() => {
            navigate("/home");
          }}
    />
``    
    As in ``<div class={pathname() != "/home" ? cssIcon : cssIconSelected}></div>`` does react to signals.

**Comment by x64Bits** [comment]
Hello @pinko64, I hope you are well and healthy, i am going to review this as soon as possible because i am dividing the props it receives due to the reactivity gain.

**Comment by pinko64** [comment]
> 

Thank you.

**Comment by pinko64** [comment]
> 

Seems to be working now. Thanks for putting the effort!
