### ISSUE TITLE
Tabler-Icons Support 

### ISSUE THREAD

**Issue by sami-azzam** [x64Bits/solid-icons#8]
Hi there, 

I was wondering if it's possible to add support for Tabler-Icons: https://github.com/tabler/tabler-icons

I used to use Tabler-icons-react with React, but now after switching to solid, I really prefer the design of Tabler-Icons over most other icon sets.

**Comment by x64Bits** [comment]
They look very interesting I'm going to take a look at the possibility of integrating it into the library, thanks!

**Comment by x64Bits** [comment]
I'm already working on sending it in the next version.

**Comment by sami-azzam** [comment]
> I'm already working on sending it in the next version.

Amazing! Can't wait :)

**Comment by x64Bits** [comment]
Hello @sami-azzam, from version 0.5.0 tabler-icons has been added, greetings.
